version: "3.8"
services:
  interbtc:
    image: "interlayhq/interbtc:1.25.0-rc1"
    command:
      - interbtc-standalone
      - --rpc-external
      - --ws-external
      - --rpc-methods
      - Unsafe
      - --dev
      - --instant-seal
    ports:
      - '9933:9933'
      - '9944:9944'
